### ISSUE TITLE
Not able to use the CraftTextDetector

### ISSUE THREAD

**Issue by kimhegg** [OlegKrymskyi/dotnet-text-recognition#1]
First of all, thank you for the code! A lot of good work here. 

But; 
I get the following error when trying an input image of 1296 x 2304 px on the CraftDetector. The same image works on the EastTextDetector. None of your demo-images works either. 

what do i have to do to make it work? 

System.ArgumentException: Length of memory (3981312) must match product of dimensions (4546560).

```
System.ArgumentException: Length of memory (3981312) must match product of dimensions (4546560).
   at Microsoft.ML.OnnxRuntime.Tensors.DenseTensor`1..ctor(Memory`1 memory, ReadOnlySpan`1 dimensions, Boolean reverseStride)
   at Microsoft.ML.Transforms.Onnx.OnnxUtils.CreateNamedOnnxValue[T](String name, ReadOnlySpan`1 data, List`1 shape)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec`1.GetNamedOnnxValueKnownSize()
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec`1.GetNamedOnnxValue()
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, INamedOnnxValueGetter[] srcNamedOnnxValueGetters, List`1 activeOutputColNames, OnnxRuntimeOutputCacher outputCache)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.<>c__DisplayClass14_0`1.<MakeTensorGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)

```

**Comment by OlegKrymskyi** [comment]
@kimhegg yes, you can't use such big image for this model. You would have to scale it to 1280x1080 A then scale back points which it would give to you.

Like, in you case
```
var ratioX = 1296 / 1280;
var ratioY = 2304 / 1080;

var points = recognize(image);

foreach(var point in points)
{
    point.X *= ratioX;
    point.Y *= ratioY;
}
```
